#ifndef GRAPHICSWIDGET_GLOBAL_H
#define GRAPHICSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRAPHICSWIDGET_LIBRARY)
#  define GRAPHICSWIDGETSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRAPHICSWIDGETSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRAPHICSWIDGET_GLOBAL_H
