#ifndef RTL_SDR_RECIVER_GLOBAL_H
#define RTL_SDR_RECIVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RTL_SDR_RECIVER_LIBRARY)
#  define RTL_SDR_RECIVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RTL_SDR_RECIVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RTL_SDR_RECIVER_GLOBAL_H
