#ifndef DATACONTROLLER_GLOBAL_H
#define DATACONTROLLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATACONTROLLER_LIBRARY)
#  define DATACONTROLLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATACONTROLLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATACONTROLLER_GLOBAL_H
