#ifndef DEMODULATOR_GLOBAL_H
#define DEMODULATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DEMODULATOR_LIBRARY)
#  define DEMODULATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DEMODULATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DEMODULATOR_GLOBAL_H
